FROM node:24.21.0-bookworm-slim@sha256:0e0ff40c39bc087845bfb27465a0df4ea419520094bc35842ff83dd8cbe6f9b6 AS runtime
FROM mcr.microsoft.com/playwright:v1.56.1-noble@sha256:f1e7e01021efd65dd1a2c56064be399f3e4de00fd021ac561325f2bfbb2b837a
COPY --from=runtime /usr/local/ /usr/local/
WORKDIR /app
RUN corepack enable pnpm && corepack prepare pnpm@10.21.0 --activate
COPY . .
RUN pnpm install --frozen-lockfile
CMD ["pnpm", "test:e2e"]
