/** Small operator-owned recovery surface: it survives a stopped web application. */
export const controlPage = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lab control centre</title><style>
:root{color-scheme:light dark;font:15px system-ui;--bg:#f8fafc;--panel:#fff;--fg:#172033;--border:#cbd5e1}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg)}main{max-width:1040px;margin:auto;padding:32px 20px}.panel{padding:24px;border:1px solid var(--border);border-radius:12px;background:var(--panel);margin:20px 0}h1{font-size:30px}h2{font-size:19px}.actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:16px}button,select{font:inherit;border:1px solid #64748b;padding:10px 14px;border-radius:7px;background:#edf2f7;color:#24374f;cursor:pointer}button.script{background:#f3edff;border-color:#7c3aed;color:#5b21b6}button:disabled{opacity:.5;cursor:default}button:focus-visible,select:focus-visible,a:focus-visible,summary:focus-visible{outline:3px solid #2563eb;outline-offset:3px}button small{font-size:10px;text-transform:uppercase;margin-right:8px}pre{max-height:380px;overflow:auto;white-space:pre-wrap;word-break:break-word;font:12px ui-monospace;padding:16px;background:var(--bg);border-radius:8px}.hint{color:#52647f;line-height:1.7}summary{cursor:pointer}.status{padding:12px 16px;border-left:3px solid #2563eb;background:var(--panel)}@media(prefers-color-scheme:dark){:root{--bg:#101827;--panel:#162135;--fg:#e6edf8;--border:#32415b}.hint{color:#a7b7d0}button{background:#25364b;color:#e0ebff}button.script{background:#352050;color:#e5d4ff}}
</style></head><body><main><h1>Lab control centre</h1><p class="hint">This page is served by the operator. It remains available while the shop and dashboard are stopped. Scripts coordinate several steps; commands affect one named service.</p><p id="message" class="status" role="status">Loading action state…</p>
<section class="panel"><h2>Entire lab</h2><p class="hint">Stop removes managed application processes, containers and networks. Stored volumes, images and logs remain. The operator stays running so you can retrieve the report and start again.</p><div class="actions"><button class="script" data-action="start" title="Start the configured guest if needed, then infrastructure, migrations, seed, owners and web readiness."><small>Script</small>Start lab</button><button class="script" data-action="restart" title="Verify complete shutdown then start, preserving durable records."><small>Script</small>Restart lab</button><button class="script" data-action="stop" title="Tear down the lab and measure stopped services and host resources."><small>Script</small>Stop lab</button><button class="script" data-action="poweroff" title="Stop the lab and configured dedicated Lima guest, preserving its disk. Full start starts the guest."><small>Script</small>Stop + release VM</button></div></section>
<section class="panel"><h2>Individual service</h2><label for="service">Service</label> <select id="service"><option>ordering</option><option>fulfillment</option><option>postgres</option><option>rabbitmq</option><option>redis</option><option>toxiproxy</option><option>web</option></select><div class="actions"><button data-action="start" data-service="yes" title="Start only the selected service."><small>Command</small>Start service</button><button data-action="stop" data-service="yes" title="Immediately stop only the selected service; durable work stays pending."><small>Command</small>Stop service</button><button data-action="restart" data-service="yes" title="Immediately stop, start and check the selected application service."><small>Command</small>Restart service</button></div></section>
<section class="panel"><h2>Cleanup evidence</h2><p class="hint">A verified stop is based on listener, Compose and scoped host observations. Free memory is a sample, not a certified idle baseline. Missing host access is reported as unavailable. The latest stop report may describe a stop before the current restart.</p><pre id="resources">No report observed.</pre></section>
<section class="panel"><h2>Action outcomes</h2><p class="hint">A request accepted with HTTP 202 is queued. Follow its ID to completed or failed before repeating an operation.</p><pre id="actions">Loading…</pre></section>
<section class="panel"><h2>Inspect and recover</h2><div class="actions"><button id="refresh" title="Read the latest action and cleanup reports.">Refresh observations</button><button id="readiness" title="Probe the configured owner and web APIs; does not start them.">Check readiness</button><button id="activity" title="Collect a bounded recent window from each available owner; missing sources are labeled.">Collect recent activity</button></div><details><summary>Inspection result</summary><pre id="inspection">Choose an inspection above.</pre></details><p class="hint">Terminal equivalents: <code>./lab start</code>, <code>./lab restart</code>, <code>./lab stop</code>, <code>./lab poweroff</code>, <code>./lab resources</code>. To stop the operator itself after saving the report, use the owned-process cleanup helper described in the runbook.</p></section></main><script>
const message=document.getElementById('message'); let sending=false,refreshing=false;
async function api(path,options){const response=await fetch(path,options);const body=await response.json();if(!response.ok)throw new Error(body.detail||'Operator request failed');return body.data;}
async function refresh(){if(refreshing)return;refreshing=true;try{const [actions,resources]=await Promise.all([api('/api/v1/actions'),api('/api/v1/resources')]);document.getElementById('actions').textContent=JSON.stringify(actions.slice(0,10),null,2);document.getElementById('resources').textContent=JSON.stringify(resources,null,2);const active=actions.find(x=>x.status==='requested'||x.status==='running');document.querySelectorAll('[data-action]').forEach(button=>button.disabled=sending||!!active);message.textContent=active?active.name+': '+active.status+' · '+active.progress:'Operator available. Inspect action outcomes and cleanup evidence below.';}catch(error){message.textContent=error.message+' · observations unavailable.';}finally{refreshing=false;}}
for(const button of document.querySelectorAll('[data-action]'))button.addEventListener('click',async()=>{const name=button.dataset.action;if(['stop','restart','poweroff'].includes(name)&&!confirm('Run '+name+'? Stored records are preserved; affected applications may disconnect.'))return;sending=true;document.querySelectorAll('[data-action]').forEach(x=>x.disabled=true);try{const action=await api('/api/v1/actions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,...(button.dataset.service?{service:document.getElementById('service').value}:{})})});message.textContent='Requested action '+action.id;}catch(error){message.textContent=error.message;}finally{sending=false;await refresh();}});
document.getElementById('refresh').addEventListener('click',refresh);
for(const [id,path] of [['readiness','/api/v1/status'],['activity','/api/v1/activity']])document.getElementById(id).addEventListener('click',async()=>{try{document.getElementById('inspection').textContent=JSON.stringify(await api(path),null,2);document.querySelector('details').open=true;}catch(error){message.textContent=error.message;}});
refresh();setInterval(refresh,2000);
</script></body></html>`;
