import { readFile, mkdir, writeFile, appendFile } from 'node:fs/promises';
import path from 'node:path';
import { format, resolveConfig } from 'prettier';
const formatting = await resolveConfig('.prettierrc.json');
const json = (value) => format(JSON.stringify(value), { ...formatting, parser: 'json' });
import { businessFiles } from '../coverage-scope.mjs';
const summary = JSON.parse(await readFile('coverage/coverage-summary.json', 'utf8'));
const entries = Object.entries(summary).filter(([name]) => name !== 'total');
const relative = (name) => path.relative(process.cwd(), name).split(path.sep).join('/');
const metrics = ['lines', 'statements', 'functions', 'branches'];
function aggregate(files) {
  return Object.fromEntries(
    metrics.map((metric) => {
      const total = files.reduce((sum, [, value]) => sum + value[metric].total, 0);
      const covered = files.reduce((sum, [, value]) => sum + value[metric].covered, 0);
      return [
        metric,
        { total, covered, pct: total ? Math.floor((covered / total) * 10000) / 100 : 100 },
      ];
    }),
  );
}
for (const file of businessFiles) {
  if (!entries.some(([name]) => relative(name) === file))
    throw new Error('Missing business coverage: ' + file);
}
const business = aggregate(entries.filter(([name]) => businessFiles.includes(relative(name))));
const systems = {};
for (const folder of [
  'apps/web',
  'apps/ordering',
  'apps/fulfillment',
  'apps/operator',
  'packages/client',
  'packages/contracts',
  'packages/runtime',
  'tools',
]) {
  systems[folder] = aggregate(entries.filter(([name]) => relative(name).startsWith(folder + '/')));
}
const report = {
  schemaVersion: 1,
  engine: 'Vitest V8',
  businessLineThreshold: 91,
  businessFiles,
  business,
  overall: summary.total,
  systems,
  files: Object.fromEntries(entries.map(([name, value]) => [relative(name), value])),
};
await mkdir('docs/badges', { recursive: true });
for (const [file, label, pct] of [
  ['business-coverage', 'business lines', business.lines.pct],
  ['unit-coverage', 'overall lines', summary.total.lines.pct],
]) {
  if (!Number.isFinite(pct)) throw new Error('Missing measured line coverage');
  const value = pct.toFixed(2) + '%',
    color = pct >= 91 ? '#4c1' : pct >= 60 ? '#dfb317' : '#e05d44';
  await writeFile(
    'docs/badges/' + file + '.svg',
    `<svg xmlns="http://www.w3.org/2000/svg" width="180" height="20" role="img" aria-label="${label}: ${value}"><title>${label}: ${value}</title><rect width="110" height="20" fill="#555"/><rect x="110" width="70" height="20" fill="${color}"/><g fill="#fff" text-anchor="middle" font-family="Verdana,sans-serif" font-size="11"><text x="55" y="14">${label}</text><text x="145" y="14">${value}</text></g></svg>\n`,
  );
}
await writeFile('coverage/system-summary.json', await json(report));
await writeFile('docs/coverage-snapshot.json', await json(report));
const table = [
  ['Business gate', business],
  ['Overall configured scope', summary.total],
  ...Object.entries(systems),
]
  .map(
    ([name, value]) =>
      `| ${name} | ${value.lines.covered}/${value.lines.total} | ${value.lines.pct}% | ${value.branches.pct}% |`,
  )
  .join('\n');
const markdown = `# Measured coverage\n\nGenerated by pnpm test:coverage from Vitest V8. The committed snapshot represents this source and test suite; use the current CI artifact for a newer run.\n\n| Scope | Covered/total lines | Lines | Branches |\n| --- | --- | --- | --- |\n${table}\n\nThe business gate requires at least 91% lines. Overall includes untested startup, HTTP assembly, JSX and host-operation tooling. Browser/integration checks do not contribute to this unit report. No general correctness score is inferred. Full per-file metrics: [snapshot](coverage-snapshot.json). Scope rationale and test limitations: [quality guide](code-quality.md).\n`;
await writeFile(
  'docs/coverage-report.md',
  await format(markdown, { ...formatting, parser: 'markdown' }),
);
if (process.env.GITHUB_STEP_SUMMARY) await appendFile(process.env.GITHUB_STEP_SUMMARY, markdown);
console.log(markdown);
if (business.lines.pct < 91) {
  console.error('Business line coverage ' + business.lines.pct + '% is below the 91% gate.');
  process.exitCode = 1;
}
